add: results input, quality check and handle pass gracefully

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,20 +19,32 @@ inputs:
     required: true
     default: "cspm.demo.accuknox.com"
 
-outputs:
-  status:
-    description: Status of the API upload.
+  results:
+    description: "Specifies which type(s) of results to output: verified, unknown, unverified, filtered_unverified. Defaults to all types."
+    required: false
 
 runs:
   using: "composite"
   steps:
     - name: Run TruffleHog
       run: |
-        docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem /pwd --json > trufflehog-results.json
+        RESULTS_FLAG=""
+        if [[ -n "${{ inputs.results }}" ]]; then
+          RESULTS_FLAG="--results ${{ inputs.results }}"
+        fi
+        
+        docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest git file:///pwd \
+        --json --fail --no-update > trufflehog-results.json || exit_code=$?
+        echo "TRUFFLEHOG_EXIT_CODE=${exit_code:-0}" >> $GITHUB_ENV
       shell: bash
 
     - name: Push report to CSPM panel
       run: |
+        if [[ ! -s trufflehog-results.json ]]; then
+          echo "No secrets found. Skipping API upload."
+          exit 0
+        fi
+        
         RESPONSE=$(curl --location 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=TruffleHog&save_to_s3=true&label_id=${{ inputs.label }}' \
             --header 'Tenant-Id: ${{ inputs.tenant_id }}' \
             --header 'Authorization: Bearer ${{ inputs.token }}' \
@@ -43,6 +55,13 @@ runs:
               echo "Error: Failed to push report to CSPM panel"
               exit 1
             fi
+      shell: bash
+
+    - name: Quality Check with exit_code
+      if: env.TRUFFLEHOG_EXIT_CODE == '183'
+      run: |
+        echo "TruffleHog found valid credentials. Failing the job."
+        exit 1
       shell: bash
 
 branding:
